# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    curl -o wizcli https://wizcli.app.wiz.io/wizcli
    chmod +x wizcli
    export WIZ_ENV=test
    ./wizcli auth --id $(WIZ_ID) --secret $(WIZ_SECRET)
    ./wizcli iac scan --path  .
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'